version: '3.4'

services:
  eurekaserver:
    image: "steeltoeoss/eurekaserver"
    ports:
      - "8761:8761"
    container_name: eurekaserver

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: rabbitmq

  urbanclap.apigateway:
    container_name: service-apigateway
    image: 3153712/urbanclap-service-apigateway:latest
    ports:
      - "8010:80"
    depends_on:
      - eurekaserver

  urbanclap.servicecatalog:
    container_name: service-catalog
    image: 3153712/urbanclap-service-catalog:latest
    ports:
      - "8001:80"
    depends_on:
      - eurekaserver

  urbanclap.bookingservice:
    container_name: service-booking
    image: 3153712/urbanclap-service-booking:latest
    ports:
      - "8002:80"
    depends_on:
      - eurekaserver
      - rabbitmq

  urbanclap.administrationservice:
    container_name: service-administration
    image: 3153712/urbanclap-admin:latest
    ports:
      - "8003:80"
    depends_on:
      - eurekaserver
      - rabbitmq

  urbanclap.serviceprovider:
    container_name: service-provider
    image: 3153712/urbanclap-service-provider:latest
    ports:
      - "8004:80"
    depends_on:
      - eurekaserver
      - rabbitmq

  urbanclap.customerservice:
    container_name: service-customer
    image: 3153712/urbanclap-service-customer:latest
    ports:
      - "8005:80"
    depends_on:
      - eurekaserver

  urbanclap.notificationservice:
    container_name: service-notification
    image: 3153712/urbanclap-service-notification:latest
    ports:
      - "8006:80"
    depends_on:
      - eurekaserver
      - rabbitmq